### ISSUE TITLE
Bug: Couldn't get metrics ..., exception 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/py-commons#29]
If an aggregated metric has a "not" section (example [1]), we will see an error[2].

[1]:
```
    - name: monitoringCPU
      metricName : containerCPU
      labels.namespace.keyword: openshift-monitoring
      metric_of_interest: value
      not:
        labels.container.keyword: kube-rbac-proxy                                                                                                                                                                                                                      
      agg:
        value: cpu 
        agg_type: avg 
      labels:
        - "[Jira: monitoring]"
      direction: 1
```

[2]:
```
2024-12-18 11:20:18,312 - Orion      - INFO - file: utils.py - line: 52 - Collecting monitoringCPU
2024-12-18 11:20:18,312 - Orion      - ERROR - file: utils.py - line: 65 - Couldn't get metrics monitoringCPU, exception 'str' object has no attribute 'items'
```
