### ISSUE TITLE
RFE: Ability to query cpu seconds metrics

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/py-commons#6]
I would like to see the "cpu seconds" counter metrics (added in [kube-burner#454]) trending over time.

Having all queries from that PR would be good:
```
* nodeCPUSeconds-Workers
* nodeCPUSeconds-Masters
* nodeCPUSeconds-Infra
* cgroupCPUSeconds-Workers
* cgroupCPUSeconds-Masters
* cgroupCPUSeconds-Infra
* cgroupCPUSeconds-namespaces
```

It will be helpful having the ability to query a single metric (i.e. a specific namespace of the metric cgroupCPUSeconds-namespaces) AND being able to query a metric and "group by" a field in the metric (i.e. group by "namespace" of cgroupCPUSeconds-namespaces).
The former allows us to track specific components, and the latter allows us to find issues in components we aren't explicitly tracking.

I am able to achieve this grouping vs filtering at the elasticsearch query level through touchstone-comparison (OK, maybe that's not a pure elasticsearch query in that case), like the following:

```
      {
        "filter": {
          "metricName.keyword": "nodeCPU-AggregatedWorkers"
        },
        "buckets": [
          "labels.mode.keyword"
        ],
...
      },
```

[kube-burner#454]: https://github.com/kube-burner/kube-burner/pull/454/files#diff-47d2378be70493e31aff2e9271cc08c4f15f53d1b7469b3dbaf702ae85773cdf

**Comment by jtaleric** [comment]
@afcollins nice, it appears we can use the report-mode metrics to do this. 

https://github.com/kube-burner/kube-burner/blob/main/cmd/kube-burner/ocp-config/metrics-report.yml#L252-L279

**Comment by afcollins** [comment]
Will have to look more into the bucket aggregation, but I was able to query the single metric just fine. So I think the current implementation is good.

**Comment by afcollins** [comment]
I am able to aggregate with a `sum`, so I think anything required has already been done.

```
    - name:  apiserverCPU
      metricName : containerCPU
      labels.namespace.keyword: openshift-kube-apiserver
      metric_of_interest: value
      agg:
        value: cpu
        agg_type: sum
      labels:
        - "[Jira: kube-apiserver]"
      direction: 1
```
